### ISSUE TITLE
If you don't provide a Limiter in a ThrottlePolicy the Check method throws an exception

### ISSUE THREAD

**Issue by curtisdurrett** [gopangea/BrakePedal#3]
Repro code:

```
    var loginPolicy = new ThrottlePolicy() // An empty constructor uses an in-memory repository
    {
      Name = "Login Attempts", // Give it a name so it can be used for logging purposes.
      Prefixes = new[] { "login:attempts" },
      PerSecond = 1,
      PerMinute = 4
    };

    var key = new SimpleThrottleKey("username");
    var check = loginPolicy.Check(key);
```

This is the exception that is thrown.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at BrakePedal.MemoryThrottleRepository.CreateThrottleKey(IThrottleKey key, Limiter limiter) in C:\Users\cdurrett\Documents\BrakePedal\src\BrakePedal\MemoryThrottleRepository.cs:line 78
   at BrakePedal.ThrottlePolicy.Check(IThrottleKey key, Boolean increment) in C:\Users\cdurrett\Documents\BrakePedal\src\BrakePedal\ThrottlePolicy.cs:line 84
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\cdurrett\Documents\BrakePedal\src\ConsoleApplication1\Program.cs:line 24
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by omar** [comment]
Thanks for pointing this out. This has been fixed in 3df2149 and version v1.0.1 has been published to NuGet.
